package OOPS

/**
 * Getters and setters in kotlin are implicit, which means they are auto generated by default
 * Getters =>we used getters to get the value of the property
 * Setters =>we use setters every time we assign the new value to the property
 * Getters and setters are Encapsulation in kotlin
 * Encapsulation => Basically means to protect or hide
 * the inner workings of class from being accessed outside
 * Encapsulation achieved through the use of access modifier, private, protected, public
 *
 * Law of encapsulation => Data's never accessed directly
 * They are generated everytime by default whenever we define property
 */

fun main(){
    var carsModel = CarsModel("Mini Cooper","Yellow",5)
    println(carsModel.model)

}

//Used this in Shared preferenec

//get => returns the value
//set => assigns the value

class CarsModel(model: String, var color: String, var doors: Int){
    var model = model
        get() {
//            println(" Test Getter")
            return field
        }
        set(model) {
            println("Test setter $model")
            field = model
        }
   }